### ISSUE TITLE
Partially created gives weird error

### ISSUE THREAD

**Issue by mccalluc** [WGBH/aws-wrapper#20]
Not sure about the exact preconditions for this, but look into it:

```
$ ruby scripts/ec2_elb_start.rb --name zyx.wgbh-mla-test.org
INFO [2015-12-04 09:24:55]: Created key pair and stored private key at /Users/chuck_mccallum/.ssh/zyx.wgbh-mla-test.org.pem. Fingerprint: 8d:0c:6a:d3:16:1b:9e:22:f4:7c:15:d3:fd:17:76:34:34:c9:9f:34
INFO [2015-12-04 09:24:55]: Created PK for zyx.wgbh-mla-test.org
INFO [2015-12-04 09:24:55]: Created group zyx.wgbh-mla-test.org, and added current user
/Users/chuck_mccallum/starting/aws-wrapper/lib/core/ec2_wrapper.rb:199:in `block in config_wait': undefined method `reservations' for nil:NilClass (NoMethodError)
...
        from /Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p481/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/client_waiters.rb:110:in `wait_until'
        from /Users/chuck_mccallum/starting/aws-wrapper/lib/core/ec2_wrapper.rb:96:in `start_instances'
        from /Users/chuck_mccallum/starting/aws-wrapper/lib/util/ec2_elb_starter.rb:13:in `start'
        from scripts/ec2_elb_start.rb:32:in `<main>'

**Comment by mccalluc** [comment]
Haven't seen this recently. Closing.
