### ISSUE TITLE
DNS lookup failed during build

### ISSUE THREAD

**Issue by mccalluc** [WGBH/aws-wrapper#36]
Not sure why this happened: Maybe I still had an old record cached locally? Have not reproduced.
```
DEBUG [2015-12-16 13:14:52]: [Aws::Route53::Client 200 0.209527 0 retries] get_change(id:"C39I947A3HT0N6")

INFO [2015-12-16 13:14:52]: Created CNAMEs
...
INFO [2015-12-16 13:15:49]: Swap instances and do it again.
/Users/chuck_mccallum/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:491:in `getresource': DNS result has no information for zzz.wgbh-mla-test.org (Resolv::ResolvError)
        from /Users/chuck_mccallum/starting/aws-wrapper/lib/core/dns_wrapper.rb:25:in `lookup_cname'
        from /Users/chuck_mccallum/starting/aws-wrapper/lib/util/swapper.rb:28:in `lookup_elb_and_instance'
        from /Users/chuck_mccallum/starting/aws-wrapper/lib/util/swapper.rb:8:in `swap'
        from /Users/chuck_mccallum/starting/aws-wrapper/lib/util/builder.rb:64:in `block in build'
        from /Users/chuck_mccallum/starting/aws-wrapper/lib/util/builder.rb:49:in `tap'
        from /Users/chuck_mccallum/starting/aws-wrapper/lib/util/builder.rb:49:in `build'
        from scripts/build.rb:46:in `<main>'
[aws-wrapper]$ dig zzz.wgbh-mla-test.org
...
zzz.wgbh-mla-test.org.  300     IN      CNAME   zzz-wgbh-mla-test-org-a-176640697.us-east-1.elb.amazonaws.com.
zzz-wgbh-mla-test-org-a-176640697.us-east-1.elb.amazonaws.com. 60 IN A 50.19.104.155
zzz-wgbh-mla-test-org-a-176640697.us-east-1.elb.amazonaws.com. 60 IN A 23.23.141.161
```
Perhaps try to build/destroy/build quickly in succession and see if that reproduces it.

**Comment by mccalluc** [comment]
@afred: I don't think we've seen this recently, so I'm closing. Feel free to reopen if you think it's still a problem.
