### ISSUE TITLE
SshOpter#just_ips fails

### ISSUE THREAD

**Issue by afred** [WGBH/aws-wrapper#50]
**Reproduce:**
  * build resources with: `ruby scripts/build.sh --name foo.wgbh-mla-test.org`
  * try to run: `ruby scripts/ssh_opt.rb --name foo.wgbh-mla-test.org --just_ips`
  * You'll get the following error:
    ```
    /Users/andrew_myers/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:491:in `getresource': DNS result has no information for openvault-qa1.wgbh-mla-test.org (Resolv::ResolvError)

        from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/core/dns_wrapper.rb:12:in `lookup_cname'
        from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/util/ssh_opter.rb:25:in `lookup_ip'
        from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/util/ssh_opter.rb:32:in `just_ips'
    ```

The `#just_ips` method expects the DNS to have been set up already, but we've factored that out of `scirpts/build.sh` doesn't do that anymore, by design.

So we need a way to retrieve IP addresses, given only the name _tag_ (not the CNAME, which may not exist).

**Done when** running `ruby scripts/ssh_opt.rb --name foo.wgbh-mla-test.org --just_ips` returns IPs associated with EC2 instances tagged with `--name`.

**Comment by afred** [comment]
NOTE: we created `Ec2Wrapper#lookup_public_ips_by_name(name_tag)`, which gets you the IPs.. however, I think we need a way to distinguish between "demo" and "production", and I don't think the tag name contains the "demo" prefix... but I could be wrong.

**Comment by afred** [comment]
Or.. you may _not_ need to know the difference between "demo" and "production", since that distinction is made _only_ after we've set up the ELB and CNAMES.
