### ISSUE TITLE
Error when using ssh_opt.rb with --ips_by_dns

### ISSUE THREAD

**Issue by afred** [WGBH/aws-wrapper#63]
Getting this error:
```
;^) ruby scripts/ssh_opt.rb --ips_by_dns --name demo.openvault.wgbh-mla.org
/Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/core/dns_wrapper.rb:68:in `lookup_dns_cname_record_set': Expected 1 record set, not 0 (RuntimeError)
	from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/core/dns_wrapper.rb:55:in `lookup_dns_cname_record'
	from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/core/dns_wrapper.rb:13:in `lookup_cname'
	from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/util/ssh_opter.rb:25:in `lookup_ip'
	from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/util/ssh_opter.rb:36:in `ip_by_dns'
	from scripts/ssh_opt.rb:39:in `<main>'
```

**Comment by mccalluc** [comment]
@afred: Most commonly, this is because the requested name isn't in the default zone: I think it would make it more obvious if we used zone names instead of IDs, and referenced that name in the error message.

**Comment by afred** [comment]
@mccalluc np.. i think i filed this, quickly figured out i needed zone id, and then forgot to close it.
