### ISSUE TITLE
--ips_by_dns option raising error even though DNS is valid

### ISSUE THREAD

**Issue by afred** [WGBH/aws-wrapper#69]
@mccalluc bug?

```
;^) ruby scripts/ssh_opt.rb --name openvault.wgbh-mla.org --ips_by_dns
/Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/core/dns_wrapper.rb:68:in `lookup_dns_cname_record_set': Expected 1 record set, not 0 (RuntimeError)
	from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/core/dns_wrapper.rb:55:in `lookup_dns_cname_record'
	from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/core/dns_wrapper.rb:13:in `lookup_cname'
	from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/util/ssh_opter.rb:25:in `lookup_ip'
	from /Users/andrew_myers/Projects/WGBH/aws-wrapper/lib/util/ssh_opter.rb:36:in `ip_by_dns'
	from scripts/ssh_opt.rb:39:in `<main>'
```

**Comment by mccalluc** [comment]
check your zone_name? Since this keeps coming up, maybe it should just scan all the zones? Or figure out the zone based on the name?

**Comment by afred** [comment]
Or just add a hint to the output in case of that error.

Or I could just remember to do it right.
